version: "3.3"
services:
    php:
        build:
            context: .
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/laravel_docker
        links:
            - mysql
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - 33061:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./mysql:/var/lib/mysql
    node:
        build:
            context: .
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules

volumes:
    db-data: ~
