version: '3.3'

services:
    nginx:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8098:80
        links:
            - fpm
        volumes:
            - ./:/var/www/laravel-docker
    fpm:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/laravel-docker
        links:
            - mysql
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - 33061:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - ./mysql:/var/lib/mysql
